# serverless.yml

service: userApp

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
  login:
    handler: index.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  create:
    handler: index.handler
    events:
      - http:
          path: create
          method: post
          cors: true
  searchAll:
    handler: index.handler
    events:
      - http:
          path: searchAll
          method: get
          cors: true
